name: prebuilt-oracle-xe
run-name: ${{ inputs.original_image_name }}:${{ inputs.original_image_version }}

on:
  workflow_dispatch:
    inputs:
      original_image_name:
        description: Original image name
        required: true
      original_image_version:
        description: Original image version
        required: true

env:
  IMAGE_NAME: ${{ github.repository }}/prebuilt-oracle-xe:${{ inputs.original_image_version }}

jobs:

  yaml-lint:
    uses: ./.github/workflows/yaml-lint.yml

  pre-build-image:
    name: Build
    runs-on: ubuntu-latest
    needs: yaml-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Start and initialize database
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --name oracle-build \
            -e ORACLE_RANDOM_PASSWORD=yes \
            -p 1521:1521 -p 5500:5500 \
            ${{ inputs.original_image_name }}:${{ inputs.original_image_version }} &

      - name: Wait for a while
        run: sleep 120s
        shell: bash

      - name: Create Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker stop -t 600 oracle-build
          docker commit -m "Image with prebuilt database" oracle-build ${IMAGE_NAME}
          docker rm oracle-build
          docker build --tag ${IMAGE} .
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ghcr.io/${IMAGE_NAME}
